nubank/nuvigator

CHANGELOG.md
example/lib/samples/modules/sample_one/navigation/sample_one_router.dart
example/lib/samples/modules/sample_one/navigation/sample_one_router.g.dart
example/lib/samples/modules/sample_two/navigation/sample_two_router.dart
example/lib/samples/navigation/samples_router.dart
lib/builder/helpers.dart
lib/src/global_router.dart
lib/src/router.dart
pubspec.yaml

This PR adds back the old abstraction of the FlowRouter, but now compatible with the new API.
Just wrap another router into the `FlowRouter` class and pass any additional parameters to create a flow creator Router.
`FlowRouters` act as normal routers when grouped into other routers, however when they match some route they will present the screen into a nested `Nuvigator` controlled by the `baseRouter`.
This allows having nested deepLink or/and routes that created nested Nuvigators dynamically. Also it's useful when some flow has not a defined starting screen and instead can be started from several of its screens, using `FlowRouter` allow this kind of behavior.

Add FlowRouter back with new API

---

CHANGELOG.md
example/lib/samples/navigation/samples_router.dart
example/pubspec.yaml
lib/src/nuvigator.dart
pubspec.yaml

Fix the bug when Android back button is pressed closing the app. Now, when the back button is pressed, the nuvigator will try to close the current page and will just close the app when doesn't have any pages to pop.

Fix the bug on didPushRoute and didPopRoute (Android only)

---

example/lib/samples/modules/sample_one/navigation/sample_one_router.dart
example/lib/samples/navigation/samples_router.dart
lib/src/nuvigator.dart
lib/src/router.dart
test/helpers.dart
test/router_test.dart

In some scenarios we'd want to use deep links as the initial route - let's say we're opening a flutter screen from a native screen and want to directly enter a screen, the canonical way to do this with flutter is to set the initialRoute property on the native side and so Material's Navigation will know that it needs to open some other path as route. The problem is that in this scenario we shouldn't expect the native screen to know the name of nuvigator's route and thus, using a deep link seems like a more abstract way to do this.
This commit adds support to set a deep link as the initialRoute value however, to do this we needed to change the deeplink resolution function (getRouteEntryForDeepLink) to be synchronous instead of asynchronous. The reason it was async before was that the …

Allow deepLinks as the initialRoute

---

lib/src/nuvigator.dart

Sometimes we may have as a root screen on Flutter a screen that is "closeable" - eg. when we launch a Flutter flow from a Native screen, the root screen on Flutter will usually be something the has a close or back to return back to the previous screen as the behaviour is much more of a "push" than a "replace". In these scenarios, trying to call a Nuvigator.pop() on this screen will fail as it's not poppable. At the same time, even when launching a full Flutter app, the root screen is something that might have a close button or behaviour and the pop() will also not work. But this is a behaviour that should by default happen as pressing the physical back button will pop this activity anyway.
So, this commit implements this behavior on the pop() method: if trying to call pop() on the …

Perform a SystemNavigator.pop() when trying to pop the root screen

---

CHANGELOG.md
lib/src/nuvigator.dart
pubspec.yaml

These PR fixes a problem in the Nuvigator.of(context) when trying to get the nuvigator out of the root router.

Fix of(context) to start the search at the last state instead of root

---

pubspec.yaml

Previously we were depending on "analyzer" 0.39.4+, however this was a version greater than the one Flutter's stable is using. This causes this library to not work on Flutter's Stable branch which is undesirable (and at this point unnecessary). As there was no real reason for this enforcing, I'm downgrading to match the version on Flutter stable.

Downgrade Analyzer dependency

---

CHANGELOG.md
analysis_options.yaml
lib/src/router.dart
pubspec.yaml
test/router_test.dart

To be able to have access to parameters containing dashes in the deepLink, those are going to be converted to camelCase.
Depends on: https://github.com/leonsenft/path_to_regexp

Add support for deepLink parameters with dashes

---

.gitignore
CHANGELOG.md
build.yaml
example/lib/main.dart
example/lib/samples/modules/sample_one/navigation/sample_one_router.dart
example/lib/samples/modules/sample_one/navigation/sample_one_router.g.dart
example/lib/samples/modules/sample_one/screen/screen_one.dart
example/lib/samples/navigation/samples_router.g.dart
lib/builder/args_class.dart
lib/builder/builder_library.dart
lib/nuvigator.dart
lib/src/helpers.dart
pubspec.yaml
test/fixtures/test_router.dart
test/fixtures/test_router.g.dart
test/navigation_test.dart

Previously, if a screen had arguments with types other than strings, a runtime error appeared when opening the route through a deep link. This PR adds support for a few basic types such as int, double, bool and DateTime.
Eventually, this could evolve to accept a custom type mapping

Add support for typed screen arguments on deep links

---

lib/builder/args_class.dart
test/navigation_test.dart

PR #40 added some misformatted files. Since format was not being checked by the CI tool, we didn't notice it until the master pipeline broke.
This PR fixes `lib/builder/args_class.dart` and `test/navigation_test.dart` formatting

Fix files format

---

CHANGELOG.md
lib/src/nuvigator.dart
pubspec.yaml

The problem here is that when the navigator is updated the observers property is replaced by the constructor observers. We should re-inject the inheritableObservers and StateTracker when the widget is updated to ensure that everything will work normally.

Fix a NavigationObserver error when the nuvigator is updated

---

CHANGELOG.md
lib/src/nuvigator.dart
pubspec.yaml

On some occasions, this was causing a NPE exception because the oldRouter was still referenced across the application.  This PR stops removing the navigator reference from oldRouters so we avoid this kind of problem in some scenarios.

Do not remove nuvigator reference from oldWidget.router on didUpdateWidget

---

README.md

This PR updates the README, both with proof-reading to make it more consistent and with removal of outdated constructs such as `FlowRoute`. It also adds information about typed parameters for deep links (added in v.6.0 and not yet documented).

Reword README and remove FlowRoute mentions

---

README.md

A previous commit accidentally "fixed" the information about parsing deep link arguments. The example was supposed to be incorrectly written to demonstrate the behaviour when this is the case.

Revert README deep link type conversion example

---

CHANGELOG.md
lib/src/screen_route.dart
pubspec.yaml

The fallback and copy methods were not considering the settings and the result is the final route without settings

Fix the nu route settings copy methods

---

CHANGELOG.md
lib/src/deeplink.dart
lib/src/nu_route_settings.dart
pubspec.yaml

When passing extra arguments to the `open` method, they were not being added to the `rawParameters` if not parsed

Fix problem of extra parameters now being propagated correctly downstream

---

README.md

With these changes, novice users can better understand how to use nuvigator from scratch. For those who have never used it before, the example "sample" can become a bit confusing because it does not correctly explain the import part of the generated file and how to generate this file. If we explain just at the end of README.md how to use build_runner, the rest of the information ends up shuffling the understanding of how to create a simple route scheme. As it is now, beginners and advanced users can understand, thus, making the documentation more accessible.

Changes to explain better a usage of nuvigator

---

CHANGELOG.md
analysis_options.yaml
example/lib/samples/router.dart
example/lib/samples/screens/home_screen.dart
example/pubspec.yaml
lib/src/legacy_nurouter.dart
lib/src/next/v1/nu_router.dart
lib/src/nuvigator.dart
lib/src/screen_type.dart
pubspec.yaml

- Allows overriding the `screenType` when calling the `Nuvigator.open` method
- Created a new class `ScreenTypeBuilder` to allow the creation of anonymous ScreenTypes

Improve screenType options

---

CHANGELOG.md
doc/next.md
example/lib/samples/router.dart
lib/src/next/v1/nu_router.dart
pubspec.yaml

Add a new option in the `NuRouter` class to call the `registerRoutes` getter only after the NuRouter was initialized. This allows for creating a NuRouter with Routes that can vary depending on some initialization logic or data fetched during it

Add option to register routes after Router initialization

---

lib/src/deeplink.dart
test/deeplink_test.dart

It is possible to deepLinks having multiple repeated query parameters encoded in it. This usually means that this query parameter should be treated as a List instead of a single value. The previous implementation was choosing one of the values provided in this case and discarding the rest.
This change implements a backwards-compatible change, where if the provided DeepLink contains the representation of a list QueryParamter, it will be returned as such. If the query parameter is not repeated, it will be returned directly (and not within a single element list)

Add support for multiple repeated query parameters

---

CHANGELOG.md
doc/migrating-to-next-api.md
doc/next.md
doc/next_PT.md
lib/src/next/v1/nu_router.dart
pubspec.yaml
test/next/fixtures/test_next_router.dart
test/next/nu_router_init_test.dart

Introduces `NuRoute.metaData` to be used as a metadata dictionary for NuRoutes
Adds `NuRouter.buildWrapper` that can be used to wrap the `builder` function of the registered NuRoutes

adding buildWrapper method to nu router

---

CHANGELOG.md
lib/src/next/v1/nu_router.dart
lib/src/nuvigator.dart
lib/src/typings.dart
pubspec.yaml
test/nuvigator_test.dart

This PR introduces the capability for controlling when a Nuvigator should rebuild.
In some cases, for instance, when there's an update in Navigation's stack, we don't want Nuvigators to be rebuild. But, in other cases, where Nuvigator's `NuRouter` is being changed, we want.
The return of `shouldRebuild` method controls if Nuvigator will be rebuilt or not.

Add support for controlling Nuvigator rebuilds

---

.circleci/config.yml
CHANGELOG.md
example/lib/main.dart
example/lib/samples/modules/composer/module.dart
example/lib/samples/modules/composer/screens/help_screen.dart
lib/src/next/v1/nu_router.dart
pubspec.yaml

The last change that allowed to disable the rebuilds of Nuvigators on certain conditions highlighted a few problems with the current approach of caching the Nuvigator instance, which could cause the App to become non-responsive to other external state changes that should trigger a re-render of the Widget.
This PR aims to fix that by instead caching in the state of the NuRoute instance, and always providing it to the builder function.

Fix NuRouteLoader by caching the NuRouter instead of the Widget

---

CHANGELOG.md
example/lib/main.dart
example/lib/samples/modules/composer/module.dart
lib/src/next/v1/nu_router.dart
lib/src/nuvigator.dart
pubspec.yaml
test/nuvigator_test.dart

This PR proposes changing the default behavior of Nuvigator to not rebuild/reload from scratch when the NuRouter instance changes, which is especially relevant for nested flow. This is motivated by the following points:
* Development experience is compromised with the current behavior, that without proper state management, at every hot-reload the flow is reset
* Some use cases of nested flows were suffering from resets when the upper state of the tree changed
While we expect this to be a fix/improvement for most cases, it's feasible to this being used as a feature for current users. Due to that, this can be considered a breaking change, and in those cases, you can provide a `shouldRebuild` function to the `Nuvigator` specifying the desired conditions to meet your previous behavior.

Update Nuvigator default behavior to not reload when NuRouter changes

---

.circleci/config.yml
example/pubspec.yaml
pubspec.yaml
test/nuvigator_test.dart

This PR has the bump of some dependencies, for flutter version 2.10

Mob plat/bump flutter 2.10

---

README.md
README_PT.md
doc/next_PT.md

```dart
class MyApp extends StatelessWidget {
@override
Widget build(BuildContext context) {
return MaterialApp(
title: 'Nuvigator App',
builder: Nuvigator.routes(
initialRoute: 'home',
screenType: materialScreenType,
routes: [
NuRouteBuilder(path: 'home', builder: (_, __, ___) => HomeScreen()),
NuRouteBuilder(path: 'second', builder: (_, __, ___) => SecondScreen()),
],
),
);
}
}
```
Add the screenType parameter in code above, without it the build fails.

Add needed paramenters in the readme use case

---

analysis_options.yaml
example/lib/main.dart
example/lib/samples/modules/composer/module.dart
example/lib/samples/modules/composer/screens/help_screen.dart
example/lib/samples/modules/composer/screens/text_composer_screen.dart
example/lib/samples/modules/friend_request/bloc/friend_request_bloc.dart
example/lib/samples/modules/friend_request/module.dart
example/lib/samples/modules/friend_request/screens/list_requests_screen.dart
example/lib/samples/modules/friend_request/screens/success_screen.dart
example/lib/samples/router.dart
example/lib/samples/screens/home_screen.dart
example/pubspec.yaml
pubspec.yaml
test/nuvigator_test.dart

This PR adds support for Dart 3
- Remove unused dependencies
- Bump flutter SDK to `>=2.17 < 4.0.0`
- Migrate lints to default `flutter_lints`

Migrate to compatible with Dart 3

---

lib/src/nu_route_settings.dart

In order to use the library on newer Flutter releases, we must migrate from the removed 'hashList' to the 'Object.hashAll' introduced in Dart 2.14.
This is safe to in all releases, as the current min SDK is Dart 2.17

Remove deprecated hash function to support Flutter 3.27
